### ISSUE TITLE
Karma Task does not fail

### ISSUE THREAD

**Issue by swenzel** [lithiumtech/karma-threshold-reporter#6]
Hey there,

I love how easy this plugin is!
However I'm getting this output:

```bash
Running "karma:dist" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket UvzB2RmVk2ev2Y4HmONy with id 75337039
PhantomJS 1.9.8 (Linux): Executed 6 of 6 SUCCESS (0.003 secs / 0.055 secs)

==================== Coverage / Threshold summary =============================
Statements   : 96.43% ( 27/28 ) Threshold : 90%
Branches     : 50% ( 1/2 ) Threshold : 60%
Functions    : 100% ( 16/16 ) Threshold : 85%
Lines        : 96.43% ( 27/28 ) Threshold : 90%
================================================================================
ERROR [Threshold]: Failed minimum coverage threshold expectations

Running "karma:distmin" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket DpAO1PZXuNX5B29gmOcv with id 69461583
PhantomJS 1.9.8 (Linux): Executed 6 of 6 SUCCESS (0.004 secs / 0.054 secs)

Done, without errors.


Execution Time (2015-01-26 09:35:50 UTC)
loading tasks      132ms  ▇▇▇▇ 6%
uglify:dist         37ms  ▇ 2%
autoprefixer:dist   43ms  ▇▇ 2%
jshint:all          78ms  ▇▇ 4%
karma:dist          1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 63%
karma:distmin      448ms  ▇▇▇▇▇▇▇▇▇▇▇ 21%
Total 2.1s
```
The reporter clearly recognizes that there is an issue with the coverage. It says ERROR and I also get the red highlight in the console... but still grunt considers the karma task as successfully completed and goes on.
This is not the case when I have issues in the tests.

Cheers
Swen

**Comment by phobetron** [comment]
I second this issue. Continuous Integration tools need a hard error to trigger a build failure.

**Comment by santthosh** [comment]
Folks, Can you please try out with the latest version (0.1.15) this should be fine, appears to be a similar issue like that https://github.com/gruntjs/grunt/commit/e35bebf6b72d3b8dfbf9a90ae58ea675d0fd0247

**Comment by swenzel** [comment]
Still no fail...

**Comment by swenzel** [comment]
However grunt exits with 1...
So I think the problem is that the tasks are not run within a subprocess and therefore the exit(1) is only evaluated when grunt itself exits... maybe there is another way to tell karma that it failed? Not sure if reporters are made for that though.

**Comment by phobetron** [comment]
Exiting with 1 should be good enough for CI tools, but it is still a little weird to see an error and then it says there are no errors :P

**Comment by swenzel** [comment]
Yeah it is weird... and also not very helpful if after karma there are some tasks that should only be executed if karma AND the threshold reporter found no problems... e.g. bump or push

**Comment by santthosh** [comment]
We use `gulp` here at Lithium and gulp-karma plugin handles it better, all you have to do is let the stream  break, hence we never ran into this issue. 

```

==================== Coverage / Threshold summary =============================
Statements   : 88.11% ( 2624/2978 ) Threshold : 95%
Branches     : 75.44% ( 906/1201 ) Threshold : 70%
Functions    : 85.84% ( 709/826 ) Threshold : 85%
Lines        : 88.11% ( 2624/2978 ) Threshold : 85%
================================================================================
ERROR [Threshold]: Failed minimum coverage threshold expectations

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
[gulp] Error in plugin 'gulp-karma': karma exited with code 1
    at done (/Users/santthosh.selvadurai/lia/LDKn/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/Users/santthosh.selvadurai/lia/LDKn/node_modules/gulp-karma/index.js:82:7)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

Can we close this ticket or let me know if we can make this better?

**Comment by swenzel** [comment]
Well to me this looks more like a hack^^ an uncaught exception and a therefore crashing process should not be the right way to fail a task...
I'd prefer to let karma fail properly i.e. just as if a test suite failed. But my concern is that a reporter plugin cannot do that. If I find the time I may have a look at this myself... in the meantime I'm using grunt-code-coverage-enforcer.

**Comment by pvieira91** [comment]
Hi guys,

I'm also using this plugin and I've run into the same issue. I have a continuos integration env configured and I want to interrupt my pipeline when this fails.
I've also noticed that, in fact, the pipeline fails (which is our main goall) however it only occurs when all the other tasks are completed or process.exit is called. It's kinda of waste and can lead to a misunderstood. 

One possible solution will be to invoke directly the process.exit(1) when we notice that the coverage is less than the expected. 

I'm gonna do a PR with that solution. I hope to get some feedback.

Thanks,
Pedro Vieira

**Comment by santthosh** [comment]
Great Thanks @pvieira91, looking forward to the PR

**Comment by pvieira91** [comment]
Hi,
I've already done the PR is the 8#
"fix: invoke directly process.exit with uncaught fatal exception code. #8"

Thanks
